### ISSUE TITLE
Some textures that need updating and some suggestions

### ISSUE THREAD

**Issue by aubymori** [shmoobalizer/DevArt_Classic#1]
* List of textures that are unchanged and need to be updated to match the classic style
    * Glow Berries
    * Kelp
    * Crimson Fungus
    * Warped Fungus
* List of unchanged sounds that need to be updated
    * Drowning damage noise
    * Burning damage noise
* Suggestions
    * Use cooked porkchop texture from Beta 1.8 as to not confuse it with Steak
    * Deepslate would make more sense if the texture was based on Cobblestone, due to the vanilla texture's rocky and bumpy-like nature

**Comment by shmoobalizer** [comment]
I still have plans to improve all the textures, in due time.

I will check out the damage sounds, thanks :)

as for the issue with pork and steak, cooked beef in the pack has a slightly dark-reddish tint to it to differentiate it, this is subtle, and intentionally so. I didn't want to change it too much from default but it needs to be differentiable from pork. In older versions of the pack, cooked pork used the B1.8 texture but I decided against this as the pack is meant to emulate Beta 1.6.

The deepslate texture does take some features from cobblestone, but subtly so. I can't make it too much like cobble as it needs to be distinct from "cobbled deepslate" which without-question must look like cobblestone.

I hope that clears some things up, in the future, please make separate tickets for each feature/bug :)
