### ISSUE TITLE
Inconsistent Spawn Egg items names

### ISSUE THREAD

**Issue by Aleksandra0056** [shmoobalizer/DevArt_Classic#14]
#### The following spawn eggs have inconsistent names:
- Armadillo Spawn Egg
- Breeze Spawn Egg
- Sniffer Spawn Egg (I don't mean the Sniffer Egg block, but the Sniffer Spawn Egg item)

#### The correct names should be:
- Spawn Armadillo
- Spawn Breeze
- Spawn Sniffer

**Comment by Swigly1** [comment]
this isn't an issues it's just something to be added in an update

**Comment by Aleksandra0056** [comment]
> this isn't an issues it's just something to be added in an update

Okay, I will close this issue as you want.
