### ISSUE TITLE
Cooked Porkchop and Steak are basically indistinguishable, unless side by side

### ISSUE THREAD

**Issue by aubymori** [shmoobalizer/DevArt_Classic#3]
There *is* a slight difference, but in gameplay, it's almost impossible to tell.
I think using the texture from Beta 1.8 is a good idea, even if it wasn't from Beta 1.6
The Beta 1.8 texture is the same as the old Cooked Porkchop texture, however it is greatly brightened (other than the outline) to differentiate from Steak.

Even if you don't use the Beta 1.8 texture, please just make them easily distinguishable from each other.

**Comment by shmoobalizer** [comment]
(for future reading, this ticket is made in the context of #1 and #2)

**Comment by shmoobalizer** [comment]
@aubymori how about this? top row is whats currently in the pack, bottom row is a new experiment I just made. Pork is left, Beef is right.

![image](https://user-images.githubusercontent.com/53633630/177021807-dd5392e9-1a98-48c6-9c62-5ea7f2478e80.png)

**Comment by aubymori** [comment]
...it's still way too similar

**Comment by shmoobalizer** [comment]
well its *supposed* to be similar, porkchops wont be changed and beef needs to at least be familiar.

I don't think anyone with well-developed eyes would be unable to distinguish these, so this is probably how it'll stay, unless somebody can provide a better solution.
